### ISSUE TITLE
The MIDI "stop all sound" oprion doesn't work

### ISSUE THREAD

**Issue by Lorsel** [Etuldan/MidiControl#32]

**Comment by Teeeeeep** [comment]
I just pulled the latest 2.0.0.3 setup from releases today and am able to reproduce this issue. To reproduce I start a persistent sound through a keybind which doesn't stop on key release. I've attempted to stop the sound via the following ways:
- Clicking the "Stop all sounds" button in the top-right of the interface (this works fine)
- Creating and executing a keybind that stops all sounds on pressed (does not work)
- Creating and executing a keybind that stops all sounds on released (does not work)
- Creating a new soundboard event that plays a sound and stops all other sounds on play (does not work)

I hope this helps, let me know if I should open a new issue instead of just necro'ing this old one.

**Comment by Etuldan** [comment]
Could you send me your profile configuration file (see https://github.com/Etuldan/MidiControl/issues/36#issuecomment-1431138926 for instructions) ? @Teeeeeep

**Comment by Teeeeeep** [comment]
> Could you send me your profile configuration file (see [#36 (comment)](https://github.com/Etuldan/MidiControl/issues/36#issuecomment-1431138926) for instructions) ? @Teeeeeep

Sure Thing!
Here's the binds from a profile I built to test this:
`{"MusicTest":{"OBSCallBacksON":[],"OBSCallBacksOFF":[],"OBSCallBacksSlider":[],"SoundCallBack":{"File":"N:\\Projects\\Sound\\Soundboard\\Wii Sports Theme.mp3","DeviceName":"Line 2 (Virtual Audio Cable)","StopWhenReleased":false,"Loop":true,"Volume":0.5623413,"StopAllOtherSounds":false,"Device":4},"MediaCallBack":null,"MediaCallBackOFF":null,"TwitchCallBackON":null,"TwitchCallBackOFF":null,"MIDIControlCallBackON":null,"MIDIControlCallBackOFF":null,"GoXLRCallBackON":null,"GoXLRCallBackOFF":null,"Mididevice":"MIDI function","NoteNumber":16,"Channel":1,"Input":1},"StopAllSBEvent":{"OBSCallBacksON":[],"OBSCallBacksOFF":[],"OBSCallBacksSlider":[],"SoundCallBack":{"File":"N:\\Projects\\Sound\\Soundboard\\Hitmarker.mp3","DeviceName":"Line 2 (Virtual Audio Cable)","StopWhenReleased":false,"Loop":false,"Volume":0.0298538357,"StopAllOtherSounds":true,"Device":4},"MediaCallBack":null,"MediaCallBackOFF":null,"TwitchCallBackON":null,"TwitchCallBackOFF":null,"MIDIControlCallBackON":null,"MIDIControlCallBackOFF":null,"GoXLRCallBackON":null,"GoXLRCallBackOFF":null,"Mididevice":"MIDI function","NoteNumber":36,"Channel":1,"Input":1},"StopAllPress":{"OBSCallBacksON":[],"OBSCallBacksOFF":[],"OBSCallBacksSlider":[],"SoundCallBack":null,"MediaCallBack":null,"MediaCallBackOFF":null,"TwitchCallBackON":null,"TwitchCallBackOFF":null,"MIDIControlCallBackON":{"StopAllSound":true,"SwitchToProfile":null},"MIDIControlCallBackOFF":null,"GoXLRCallBackON":null,"GoXLRCallBackOFF":null,"Mididevice":"MIDI function","NoteNumber":35,"Channel":1,"Input":1},"StopAllRelease":{"OBSCallBacksON":[],"OBSCallBacksOFF":[],"OBSCallBacksSlider":[],"SoundCallBack":null,"MediaCallBack":null,"MediaCallBackOFF":null,"TwitchCallBackON":null,"TwitchCallBackOFF":null,"MIDIControlCallBackON":null,"MIDIControlCallBackOFF":{"StopAllSound":true,"SwitchToProfile":null},"GoXLRCallBackON":null,"GoXLRCallBackOFF":null,"Mididevice":"MIDI function","NoteNumber":34,"Channel":1,"Input":1},"StopAllPressRelease":{"OBSCallBacksON":[],"OBSCallBacksOFF":[],"OBSCallBacksSlider":[],"SoundCallBack":null,"MediaCallBack":null,"MediaCallBackOFF":null,"TwitchCallBackON":null,"TwitchCallBackOFF":null,"MIDIControlCallBackON":{"StopAllSound":true,"SwitchToProfile":null},"MIDIControlCallBackOFF":{"StopAllSound":true,"SwitchToProfile":null},"GoXLRCallBackON":null,"GoXLRCallBackOFF":null,"Mididevice":"MIDI function","NoteNumber":33,"Channel":1,"Input":1}}`

Five keybinds in total, the first starts music, the next four are combinations of attempting to stop the music that was played.

Sidenote: Absolutely love this program, may look through the source and make my first pull request on git since I find it so useful.
Hope this helps!

**Comment by Teeeeeep** [comment]
Alrighty, had a chance to pull the source and take a look (made another issue about a missing file from the repo, sorry >.<).

After a repro test locally, turns out the device I'm using to send MIDI buttons is actually sending the value as a slider (no idea why, really need to write the Android app I use myself so it gets done right). Anyway, on `MIDIListener.cs:359` there's a handler for slider events that isn't checking if `entry.Value.SoundCallBack.StopAllOtherSounds` is true and stopping other sounds when playing a new one; there's also no check for if `entry.Value.MIDIControlCallBackOn` has a value set. I've added both of these in my local test and they both work fine, though I've no idea what the knock-on effects of allowing these events to fire on a slider is okay. 

I'd love to hear your thoughts on that, hope you're having a wonderful day!

**Comment by Etuldan** [comment]
Indeed, if your buttons are considered as slider, it will not work as it.
What it the manufacturer/productName of your midi device ?

**Comment by Teeeeeep** [comment]
> Indeed, if your buttons are considered as slider, it will not work as it. What it the manufacturer/productName of your midi device ?

I'm using an android app called Daw It since I don't have dedicated midi hardware at my desk at all times, but I do always have a bunch of android devices floating around. I'm switching to TouchDaw for more of my stuff but that's tedious setup time I don't enjoy spending, but it will definitely address the issue. In the meantime, I've modified local source to allow sliders to trigger soundboard events on press and release which seems to be 100% functional, though I'm not a very rigorous QA tester.

**Comment by Etuldan** [comment]
Could you provide the GooglePlayStore url of the "DAW" mobile app ?
And don't hesitate to create and pull request the fix ! I'll definitely look into it.
