### ISSUE TITLE
Stop All Sounds 

### ISSUE THREAD

**Issue by Prosti95** [Etuldan/MidiControl#6]
I would love to use Midicontrol as soundboard. When I assign the "stop all sounds" function to one of the buttons on my midi keyboard the application force closes without any warning or other messages on press of said key. The speaker Icon in the GUI works flawlessly for stopping the sounds.

Is there an older version without that behavior available? Or any way to fix this?

**Comment by paccerdk** [comment]
It seems to be a bug with the program. 
I noticed that if you go back and modify your newly created "stop all sounds" midi keybind and look under MIDIControl, the "switch to profile" has automatically become selected, even though it shouldn't, and the profile selected is blank.

Deselecting this does not work, as it just switches back on... however, if you select your profile (probably "Default" in most cases), click modify, and then SAVE your profile - it works without crashing.

Don't forget to save your profile from now on, before pressing this bind again, since it will roll back to your saved profile and you lose your unsaved changes if you don't.

**Comment by Prosti95** [comment]
Nice. This works for me. Thanks a lot.
At least the bug and a workaround are found.

**Comment by jboby93** [comment]
i created a pull request to address this issue #8
